### ISSUE TITLE
Missing Dotfiles

### ISSUE THREAD

**Issue by Xopper** [0sssama/labs-cluster#5]
It would be awesome if there is **.env.example** and **.editorconfig** .

**Comment by olabrahmi** [comment]
Hello!

Yes, we'd love to add those files to our project. I already put an example for a **.env** file in the **README** but I still think that a **.env.example** file is necessary.

We'd love it if you could contribute and work on adding those files to the repository. Fork it and make a pull request, we'd love to add your name to the contributors list!

Thanks a lot.
